### PR TITLE
#1 simple error handling common middleware.

### PR DESCRIPTION
**Pull request by sugan0tech**

### CODE REVIEW

**Comment by alanansari** [comment]
Replace the errors inside the controller with this too.

**Comment by sugan0tech** [comment]
@alanansari  sure.

**Review by alanansari — CHANGES_REQUESTED** [review]
Add to each error

**Comment by alanansari** [comment]
@sugan0tech u still working on this?

**Comment by sugan0tech** [comment]
@alanansari will do, little bit off with work days. Any deadlines?. if can you assign priority too with other following issues.

**Comment by sugan0tech** [comment]
@alanansari needs to clarify some doubts. is there any other way to have more communication? instead of spamming here.

**Comment by alanansari** [comment]
> @alanansari needs to clarify some doubts. is there any other way to have more communication? instead of spamming here.

U can join our discord

**Pull request closed without merging**
